apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag2-oct17-2
  janus-idp.io/tekton: rag2-oct17-2
  backstage.io/kubernetes-id: rag2-oct17-2
  backstage.io/kubernetes-namespace: chabot2-oct17-1 
  app.kubernetes.io/part-of: rag2-oct17-2
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
